### ISSUE TITLE
modes / hybrid modes

### ISSUE THREAD

**Issue by Grueslayer** [OXY2DEV/markview.nvim#94] opened 2024-08-08 19:31 UTC
**Describe the bug**

In the README is a typo, it must read `concealcursor` instead of `conecalcursor`.

Using the mentioned minimal config for insert mode gives me a weird behavior:

If I'm in insert mode there is NO conceiling at all. While going through the lines with cursor keys up/down each line left behind becomes displayed with conceiling AND normal text.

If I switch the order to `modes = { "n", "i", "c", "no" },` insert mode runs fine, normal mode has still no conceiling at all.

**Are you using a distro?**
No

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document.
3. Go to Insert mode

**Expected behavior**
Full Conceiling in Normal mode, Hybrid mode in Insert

**Actual behavior**
No Conceiling at all in Insert, with given example from README strange display of "visited" lines.

**Screenshots**
n/a

**Neovim version**
NVIM v0.11.0-dev-226+g721551210

**Additional context**
Currently using DEV branch.

**Comment by OXY2DEV** [comment] 2024-08-08 19:42
> If I'm in insert mode there is NO conceiling at all. While going through the lines with cursor keys up/down each line left behind becomes displayed with conceiling AND normal text.

That's caused by the `on_enable` function not working.

**Comment by Grueslayer** [comment] 2024-08-08 21:06
@OXY2DEV of course I corrected the typo but the situation is as described.

**Comment by OXY2DEV** [comment] 2024-08-09 01:15
> @OXY2DEV of course I corrected the typo but the situation is as described.

Are you still in the dev branch? Dev bran

**Comment by OXY2DEV** [comment] 2024-08-09 13:22
Dev branch has been updated. So, I am closing the issue.

**Closed by OXY2DEV** 2024-08-09 13:22 UTC
Labels: bug

**Comment by Grueslayer** [comment] 2024-08-09 16:37
Thanx, running fine now.
