### ISSUE TITLE
🐞 Bug:  Some code blocks aren’t rendered properly

### ISSUE THREAD

**Issue by ibhagwan** [OXY2DEV/markview.nvim#213] opened 2024-12-03 04:39 UTC
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

Easier to explain with images:

The code block:
![IMG_2763](https://github.com/user-attachments/assets/2778acaf-f22f-47f7-8504-f3124a6ffa3d)

Renders as:
![IMG_2762](https://github.com/user-attachments/assets/ffe4cab6-8773-41aa-99ff-e5233b0151f2)

### Steps to reproduce the issue:

Open [fzf-lua’s README](https://github.com/ibhagwan/fzf-lua/blob/main/README.md) and scroll the various code blocks.

### Neovim version:

0.10.2

**Comment by OXY2DEV** [comment] 2024-12-03 04:49
This is a duplicate of #196.

See your `tree-sitter` config. Ensure you have the *latest* version of the parsers.

**Closed by OXY2DEV** 2024-12-03 04:49 UTC
Labels: bug

**Comment by ibhagwan** [comment] 2024-12-03 05:01
> This is a duplicate of #196.

Sorry for the dup, I missed that one as I only searched open bugs.

> See your `tree-sitter` config. Ensure you have the _latest_ version of the parsers.

I updated treesitter and all parsers to latest with `:TSUpdateSync`, don’t have any special config for markdown (+inline), I’ll uninstall and install perhaps it would help.

**Comment by OXY2DEV** [comment] 2024-12-03 05:04
If issue persists you can switch to the `dev` branch.

**Comment by ibhagwan** [comment] 2024-12-03 05:07
> If issue persists you can switch to the `dev` branch.

Found the issue, it wasn’t the parsers, I had `highlight = { disable = … }` for markdown, it was confusing as some of the code blocks didn’t have this issue, anyways looking good now ty :)

**Comment by OXY2DEV** [comment] 2024-12-03 05:25
> it was confusing as some of the code blocks didn’t have this issue

Because they are handled by `markdown_inline`.

**Comment by ibhagwan** [comment] 2024-12-03 05:30
> > it was confusing as some of the code blocks didn’t have this issue
> 
> Because they are handled by `markdown_inline`.

That makes perfect sense as I only had markdown hl disabled.
