### ISSUE TITLE
Preview is duplicated when use Ctrl+^

### ISSUE THREAD

**Issue by vunhatchuong** [OXY2DEV/markview.nvim#12] opened 2024-06-30 00:16 UTC
Everytime I press `Ctrl+6` to switch to previous buffer every previewed things are duplicated.

**First time view a markdown file:**
![image](https://github.com/OXY2DEV/markview.nvim/assets/20581504/517b34b1-d0ad-47d6-90b3-32e8114fe2da)

**Go to another file then press `Ctrl+6`:**
![image](https://github.com/OXY2DEV/markview.nvim/assets/20581504/013a0786-12e6-4123-b772-fce8d04c1968)

**Do it again:**
![image](https://github.com/OXY2DEV/markview.nvim/assets/20581504/8230a304-a96b-44b6-ac41-4d19429fc01b)

**Comment by OXY2DEV** [comment] 2024-06-30 00:55
This is a duplicate of #4 and will be fixed in the next update.

**Comment by OXY2DEV** [comment] 2024-07-05 12:44
I have updated the plugin. Can you check if the issue still occurs?

**Closed** 2024-07-05 13:10 UTC
